version: '3.3'

services:
  app:
    depends_on:
      - app_db
    image: wp-graphql-rankmath:latest-wp${WP_VERSION-5.9}-php${PHP_VERSION-8.0}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-rank-math'
      - './.log/app:/var/log/apache2'
    env_file:
      - .env
    environment:
      WP_URL: http://localhost:8091
      USING_XDEBUG: ${USING_XDEBUG:-}
    ports:
      - '8091:80'
    networks:
      local:

  app_db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      wordpress
      MYSQL_USER:          wordpress
      MYSQL_PASSWORD:      wordpress
    ports:
      - '3306'
    networks:
      testing:
      local:

  testing:
    depends_on:
      - app_db
    image: wp-graphql-rankmath-testing:latest-wp${WP_VERSION-5.9}-php${PHP_VERSION-8.0}
    volumes:
      - '.:/var/www/html/wp-content/plugins/wp-graphql-rank-math'
      - './.log/testing:/var/log/apache2'
    env_file:
      - .env
    environment:
      SUITES: ${SUITES:-}
    networks:
      testing:

networks:
  local:
  testing:
