<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitbf31fcfbd71f02b8733e2b41ad240ef3
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WPGraphQL\RankMath\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WPGraphQL\RankMath\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitbf31fcfbd71f02b8733e2b41ad240ef3', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WPGraphQL\RankMath\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitbf31fcfbd71f02b8733e2b41ad240ef3', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WPGraphQL\RankMath\Vendor\Composer\Autoload\ComposerStaticInitbf31fcfbd71f02b8733e2b41ad240ef3::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \WPGraphQL\RankMath\Vendor\Composer\Autoload\ComposerStaticInitbf31fcfbd71f02b8733e2b41ad240ef3::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
