blank_issues_enabled: true
contact_links:
  - name: General Support Request
    url: https://github.com/AxeWP/wp-graphql-rank-math/discussions
    about: For general help requests, create a new topic in Github Discussions
